### ISSUE TITLE
Wrap QWebEnginePage's contentsSizeChanged signal on Qt5.8

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/qtpy#108]
Right now the signal ``contentsSizeChanged`` brokes all compatibility with applications that depend on QWebPage's ``contentsChanged`` signal. An example of this is presented on spyder-ide/spyder-terminal#48

**Comment by goanpeca** [comment]
Ok, so lets make a patch that adds the most recent signal to the classes so that don't have them and connect those two signals together if they have the signature or connect to an intermediate helper function where the signatura can be adjusted and then the signal re-emitted.

Then lets use the latest signal on our spyder code. The idea is to have the code that follows the latest Qt version

**Comment by andfoy** [comment]
@goanpeca The idea is to wrap ``contentsChanged`` as ``contentsSizeChanged``, so that the last signal name prevails? _i.e.,_ On Spyder Terminal the signal should be ``contentsSizeChanged`` instead of ``contentsChanged``

**Comment by goanpeca** [comment]
The idea is to include the newest signal in the old classes (Qt<5.8) so that people are encouraged to code using the latest signal. So in this case `contentsChanged` is on Qt 5.8 and before we had 1 contentsSizeChanged` ? and they do the same?

**Comment by andfoy** [comment]
According to http://stackoverflow.com/questions/41966825/how-to-catch-and-handle-qtwebenginepage-content-changing both signals are different, and actually  ``contentsChanged`` was removed on 5.8

**Comment by andfoy** [comment]
The reimplementation should be done at a Javascript level

**Comment by andfoy** [comment]
Closing because the signals are unrelated.
