### ISSUE TITLE
Imported modules are not respected

### ISSUE THREAD

**Issue by hiaselhans** [spyder-ide/qtpy#222]
I found an issue with qtpy:

when i already have pyside2 imported somewhere it doesn't pick pyside2 but some other implementation.

I think this line has the wrong bool check:
https://github.com/spyder-ide/qtpy/blob/673fb93f5c126c6af1c2cb455da95c7e8b82cc62/qtpy/__init__.py#L119-L129

i think that logic should evaluate if FORCE_QT_API __is__ None

**Comment by hiaselhans** [comment]
ping @goanpeca @altendky 

i thiink this is quite obvious

**Comment by altendky** [comment]
I agree that it seems odd and counter to the comment.

https://github.com/spyder-ide/qtpy/blob/673fb93f5c126c6af1c2cb455da95c7e8b82cc62/qtpy/__init__.py#L117-L118

Yet the contents of the `if` is run when `FORCE_QT_API` is set and the contents looks at what has been imported instead of disregarding it.  Simple enough to make them match but `FORCE_QT_API` isn't documented and this has been this way for two years so...  for the moment I'm going to leave this to the admins.  If we were on the verge of release or such I would probably push more specifically to get this resolved.

**Comment by hiaselhans** [comment]
hi @altendky 

thx for your comments.
To me it's clearly a bug. i can file a pr if it helps.

Here is what happened on my side:
I am using a small library which is itself depending on qtpy for generic imports.
So, i am using pyside2 but not setting `FORCE_QT_API` leads to the logic detecting my previously imported pyside2 being skipped.
The only way to make it work in my project is to `os.environ.setdefault('QT_API', 'pyside2')` prior to importing the project. In fact setting an undocumented env variable :)

I'm okay with it, but clearly qtpy is failing it's main purpose for reusable qt libraries here...

**Comment by altendky** [comment]
I didn't mean to be dragging my feet on fixing an issue.  I just have no more authority here than you do.  So, there's only so much use in me jumping in.

**Comment by hiaselhans** [comment]
sorry @altendky for dragging you into this. :)
i only checked recent commits, found and tagged you....

but, still looking at a way to proceed:

with #230 set up, who can i ping then? I'd really like to see this Bugfix upstream because some libraries depend on qtpy and i'd like to get rid of os.setenv's...!

**Comment by altendky** [comment]
The admins are likely subscribed to the repo anyways.  You could take a stab in [the gitter](https://gitter.im/spyder-ide/public) I guess.

**Comment by tlambert03** [comment]
+1. would love to see this fixed
