### ISSUE TITLE
If I were to help...  what would you want done?

### ISSUE THREAD

**Issue by altendky** [spyder-ide/qtpy#226]
To be blunt, I'm interested in getting #217 merged and released...  but, I would be happy to work on whatever \_you\_ want worked on if it might hopefully eventually lead to some form of what I want.  `:]`  Need some help with #208?  Maybe something in another project?  Or do the work of reviewing other people's PRs here?  Just let me know if there's something I can do to help start QtPy moving a bit again.

And sure, I understand that sometimes even just delegating can take more time and effort than we have available.  But, I figured I'd offer.

Thanks for your time.

Cheers,
-kyle

**Comment by dalthviz** [comment]
Since https://github.com/spyder-ide/qtpy/pull/337 (which includes the work done at https://github.com/spyder-ide/qtpy/pull/217 and fixed https://github.com/spyder-ide/qtpy/issues/216) was merged I will close this one. Again thank you so much @altendky for your interest in helping out the project, submitting https://github.com/spyder-ide/qtpy/pull/217 and the time you put there :)
