### ISSUE TITLE
Compat shiboken and sip like Qt.py

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [spyder-ide/qtpy#302]
Qt.py compat with shiboken and sip modules

```python
from Qt.compat import wrapInstance,isValid
```

This is very helpful in some case.

**Comment by CAM-Gerlach** [comment]
@dalthviz , is this something we want to consider?

**Comment by dalthviz** [comment]
After checking this a little bit I think it could be ok :+1: 

This should be the addition of two functions with the respective handling of the different bindings in `qtpy/compat.py` following the current compat functions naming so something like `isvalid` and `wrapinstance` (not totally sure of the `isvalid` name since with `sip` the function name is `isdeleted` I think)

If you want to help with this @FXTD-ODYSSEY let us know!

**Comment by zjp** [comment]
My organization has a hand-rolled Qt shim, and I'd love to contribute some of our work back to the open source community. Do you mind if I take a stab at it? We have methods to deal with this that I wouldn't mind adding to `qtpy/compat.py` and sending you a PR.

**Comment by ccordoba12** [comment]
Hey @zjp, that sounds great! Please go ahead and push a PR for this.

**Comment by zjp** [comment]
Great! I have a handful of different functions to add, so I'll add them as separate PRs.
