### ISSUE TITLE
`PySide6.QtSvgWidgets` not exposed

### ISSUE THREAD

**Issue by ralienpp** [spyder-ide/qtpy#351]
The `QtSvgWidgets` module is not available in QtPy (tried it with 2.1.0), it would be nice to add it, to avoid importing directly from underlying library (i.e. `from PySide6 import QtSvgWidgets`).

**Comment by dalthviz** [comment]
Hi @ralienpp thank you for the feedback! The upcoming version 2.2.0 will have this module as well as a bunch other missing modules when using version 2.1.0.

The missing modules were added with PR https://github.com/spyder-ide/qtpy/pull/344 ([`QtSvgWidgets` included](https://github.com/spyder-ide/qtpy/pull/344/files#diff-332adca5ca0217d1f742d3c0e26e06e65e22d4cd280ef0d9fe770a3015c9249b))

I will close this as fixed by https://github.com/spyder-ide/qtpy/pull/344 but if you have any other comment or question let us know!
