### ISSUE TITLE
Test PySide6 6.4.x

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#375]
Add PySide6 6.4.0 to the test suite since some changes regarding enums could be causing problems like #373

**Comment by CAM-Gerlach** [comment]
Lmk if you need a hand with this—basically, we can either add a new matrix job under `include`, or you can just bump the `pyside6-version` running on `windows-latest`/3.10/use-conda: No to 6.4 instead of 6.3, so we capture the full range of supported versions, which I believe was the reason we did so in the first place (and we have our other jobs running on the 6.2 LTS).

**Comment by CAM-Gerlach** [comment]
For the extra packages, if at least their `major.minor` versions match the main binding package, we can re-use those `env` variables rather than adding separate ones per package, but otherwise we can either just add them individually, or as a single environment variable that is a string of extra dep requirements for specific matrix slot(s).

**Comment by dalthviz** [comment]
I think you have a clear plan for this so if you want to help go ahead @CAM-Gerlach :+1:

**Comment by CAM-Gerlach** [comment]
Sure; I've opened #376 with the initial preliminary changes to bump the upper bound up to 6.4, and then we can address any test failures from there (which I might need help with, if they're not so easy to fix), and move to adding the optional deps after that (either there or in a separate PR).
