### ISSUE TITLE
Support PyPy

### ISSUE THREAD

**Issue by nrbnlulu** [spyder-ide/qtpy#399]
Could this project support pypy?

**Comment by CAM-Gerlach** [comment]
Hey, so the QtPy package itself supports PyPy to the extent that the bindings it wraps (PySide2, PySide6, PyQt5 and PyQt6) do; it's just pure-Python code shipping pure-Python wheels and noarch conda packages, so it will install and import right now, with both pip and Conda, and as far as I can tell, it doesn't itself use anything CPython-specific.

However, in order for it to actually be practically useful, the various Qt binding packages need to be working and available with PyPy. It seems there are wheels now available for the latest PySide6 >=6.4.0, but I don't see any for PySide2, PyQt5 or PyQt6, and it appears none of the bindings are built for PyPy on Conda-Forge either. 

Furthermore, I tested the one available package, the PySide6 6.4 wheel, on the Conda-installed PyPy (with everything else pure wheels) and unfortunately while I could import the base `PySide6` package and `qtpy`, attempting to import PySide6.QtGui or qtpy.QtGui resulted in `ImportError: The specified procedure could not be found` at least on my Windows test machine, so it seems likely we'll need to set up a parallel CI pipeline running an upstream pypy build instead of our Conda one to even try to test it.

Given that there's likely little to nothing we can do on QtPy's end to affect (for good or ill) PyPy compatibility, as opposed to that being almost entirely a property of the bindings themselves, it's not clear that it's worth setting up a whole parallel CI pipeline on our end at this point, especially when we're nearly entirely blocked on the bindings. It would likely instead be much more productive to reach out to Riverbank (PyQt6) or QtC (PySide6) to request support for PyPy in the wheels, and to the PyQt and PySide Conda feedstocks to get support added there. Once that happens, QtPy should support PyPy by default (and we could potentially consider adding CI job(s) and formally declaring support in the PyPI Trove classifiers).

@dalthviz , @ccordoba12 , what do you think?

**Comment by ccordoba12** [comment]
I don't think there's anything we can do about this, sorry. QtPy is already compatible with PyPy but there are no Python Qt bindings available for it, so it can't do its job. However, that's not something we can solve here.

**Comment by dalthviz** [comment]
Closing this one since there's anything we can do about this from the QtPy side
