### ISSUE TITLE
Is it better to use `QtCore.qVersion()` as the `QtCore.__version__`?

### ISSUE THREAD

**Issue by StSav012** [spyder-ide/qtpy#406]
It seems that `QtCore.qVersion()` and `QtCore.QLibraryInfo.version().toString()` (since 5.8) report the actual Qt version that comes with a python package. I haven't found much on it, though. This way, there would be no discrepancy between the versions of `PyQt5`, `PySide2`, and `Qt` altogether. Moreover, since [`QVersionNumber`](https://doc.qt.io/qt-6/qversionnumber.html) supports comparisons, there in no need in `packaging` package, which apparently provides only `parse` function.

What concerns me is that there might be a good reason of `PyQt5` version growing faster than the one of `Qt`. Indeed, `PyQt5==5.9.2` comes with `Qt5==5.12.6`, but there is still `Qt5==5.15.2`, whereas `PyQt5==5.15.9` already.

**Comment by CAM-Gerlach** [comment]
> It seems that `QtCore.qVersion()` and `QtCore.QLibraryInfo.version().toString()` (since 5.8) report the actual Qt version that comes with a python package.

Okay, great. It seems my testing confirms that both these are present on both PyQt and PySide 5.15 on Windows. However, is there an advantage to using the string version of this as the source for `__version__`, instead of the existing PySide2 `__version__`, or `QT_VERSION_STR` for PyQt5? Users can already call both directly if they need them, since they are consistent on both bindings.

> This way, there would be no discrepancy between the versions of PyQt5, PySide2, and Qt altogether.

I'm not sure what you mean, sorry—with both the existing `PyQt5.QT_VERSION_STR`/`__version__` methods, and two you suggest above, I get the same consistant Qt version on all of them.

> Moreover, since [`QVersionNumber`](https://doc.qt.io/qt-6/qversionnumber.html) supports comparisons, there in no need in `packaging` package, which apparently provides only `parse` function.

It's still needed for other version comparisons, specifically OS versions and binding versions, used a number of places in ``__init__.py``, so we'd still have to keep it anyway—though that is nice to know.

> What concerns me is that there might be a good reason of `PyQt5` version growing faster than the one of `Qt`. Indeed, `PyQt5==5.9.2` comes with `Qt5==5.12.6`, but there is still `Qt5==5.15.2`, whereas `PyQt5==5.15.9` already.

Not sure exactly what you mean here, either—I thought we're talking about the Qt version, not the binding versions here (which are of course entirely different things).
