### ISSUE TITLE
How to catch QtBindingsNotFoundError

### ISSUE THREAD

**Issue by cbrnr** [spyder-ide/qtpy#412]
This is perhaps a stupid question, but assuming I have only `qtpy` installed and *no* Qt bindings – how am I supposed to catch the `QtBindingsNotFoundError` for `import qtpy`?

**Comment by CAM-Gerlach** [comment]
Good question!

As of now, you could try-except the `import qtpy` line catching `RuntimeError`, which `QtBindingsNotFoundError` subclasses, i.e.

```python
try:
    import QtPy
except RuntimeError:
    ...
```

The only other error raised by `qtpy.__init__` that subclasses this error class are the checks for incompatible Qt binding versions, which are conceptually similar in nature; it being raised by a the bindings themselves on `import` seems unlikely, but not impossible (and still likely traceable to a similar cause, broken or incompatible bindings installed).

If you want to be sure that the error class is that specific one, you can get the error message class from the `type()` of the exception object, and use e.g. string comparison from that:

```python
try:
    import QtPy
except RuntimeError as error:
    if type(error).__name__ == "QtBindingsNotFoundError":
        ...
    else:
        raise
```

A bit inelegant, but gets the job done.

To note, since the error is fundamentally an `ImportError`, we should probably add `ImportError` to the bases of `QtBindingsNotFoundError`. Then you'd be able to catch that specific error, and those directly conceptually tied to it, with the more precise and idiomatic

```python
try:
    import QtPy
except ImportError:
    ...
```

Would you like to submit a PR?

@dalthviz , any other ideas here?

**Comment by ccordoba12** [comment]
> To note, since the error is fundamentally an ImportError, we should probably add ImportError to the bases of QtBindingsNotFoundError

I agree with this. And perhaps we should make `QtBindingsNotFoundError` only inherit from `ImportError`?

**Comment by cbrnr** [comment]
I think inheriting from `ImportError` is a great idea! I can submit a PR.

The other option would be to let users `import qtpy` without any exception, and raise the `QtBindingsNotFoundError` at a later point.

**Comment by cbrnr** [comment]
So you are saying you don't want to change anything and users have to catch a `RuntimeError`? Or base `QtBindingsNotFoundError` on both `RuntimeError` and `ImportError`?

**Comment by dalthviz** [comment]
Should we also add some documentation about this on the `README`? Like a section about possible exceptions that `qtpy` could raise and a suggested way on how to handle them?

**Comment by CAM-Gerlach** [comment]
Yeah, that would be a good idea—#395 includes your suggestion of documenting the exception hierarchy, and from this we could include the suggested workarounds from my post above. I just haven't quite found the time yet between my research, teaching and various FOSS responsibilities, sorry.
