### ISSUE TITLE
Coveralls config needs to be updated

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/qtpy#426]
Not totally sure why but seems like the coverage reports started to be handled differently. After doing a merge with master a bunch of failed checks appeared: https://github.com/spyder-ide/qtpy/commit/bc7a3c746c88ea3e5d8f02818763636bae807523 

Checking the coveralls page seems like now the coverage is associated to the path where the report is located instead of being aggregated?:

![image](https://user-images.githubusercontent.com/16781833/231014486-22fb9a41-7e5e-496e-adc0-38a84a4a3961.png)

Could this be related with the change to use mamba or could it be related with some updates on the Coveralls tools that require for us to update the coverage upload config? What do you think @CAM-Gerlach?

**Comment by CAM-Gerlach** [comment]
As far as I'm aware, it was entirely independent as a problem was initially reported on https://github.com/spyder-ide/qtpy/pull/421#issuecomment-1500093992 where the coverage dropped a bunch and the check was failing, and now that check is not appearing in the checks list at all for any recent-ish PRs (even before that change). And I'm not aware of any mechanism by which the mamba change could have influenced it as it doesn't use mamba at all, it uses its own isolated pipx environment (since PR #268 ). I did change the `bash` invocation for its step to use `-e`, so that any error would be reported, but it shouldn't have any effect on the functioning of the check and the issue had apparently happened prior to that.

So, I'm really not sure; I'm not an expert at coveralls (or coverage checks in general) as I don't really use them much myself, and with everything else on my plate right now I'm not sure how much time I have to muck with it more at the moment after not seeing any obvious indication of what's going on in the build logs.

**Comment by dalthviz** [comment]
Note: Maybe something to check for the situation here - https://github.com/lemurheavy/coveralls-public/issues/1390
