### ISSUE TITLE
Add documentation for methods or helpers that are specific to qtpy

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/qtpy#61]
This includes documenting
- `from qtpy.QtCore import Signal, Slot`
- The use of the openfiledialog openfolderdialog helpers (study the option of overloading QFileDialog... which would also need documentation as it would change the default behavior)
- Where to find the Qt version `from qtpy.QtCore import __version__`

**Comment by Nodd** [comment]
That could be done directly in the readme because it's quite important.

**Comment by goanpeca** [comment]
Agreed!

**Comment by goanpeca** [comment]
Ok I will add this to the Readme now based on #76.

@Nodd, we never claimed to be 5.3 or something compatible, I think the aim was to be 5.6+, thoughts?

**Comment by CAM-Gerlach** [comment]
@dalthviz I can try to help with this, but given I'm not a Qt expert (both a benefit and a downside when writing user docs), I'll need a little more detail on what you want said here:

* Beyond just letting people know to import `Signal` and `Slot` from here, are there QtPy-specific syntax or semantics that need to be described, or something else we want to say?
* I assume this is related to #26 ? Basically, we'd need basic documentation for these QtPy-specific helper functions? Since I'm not familiar with them, beyond just elaborating on the API and anything else the docstrings I'd need some help here with what to say.
* This seems pretty streightforward

**Comment by dalthviz** [comment]
>Beyond just letting people know to import Signal and Slot from here, are there QtPy-specific syntax or semantics that need to be described, or something else we want to say?

Besides the things described at the OP probably some description for the env variables that `QtPy` uses (`FORCE_QT_API`, `QT_API`) as well as state variables available (`PYQT5`, `PYQT6`, `PYSIDE2`, `PYSIDE6`, etc) could be nice (also letting clear that we are trying to follow Qt5 layout for things, so for example `pyqtSlot` -> `Slot`)

> I assume this is related to Get rid of getexistingdirectory and patch QFileDialog? #26 ? Basically, we'd need basic documentation for these QtPy-specific helper functions? Since I'm not familiar with them, beyond just elaborating on the API and anything else the docstrings I'd need some help here with what to say.

Yes, related in the sense that following what is decided there (keeping it as it is, adding aliases to those functions or patching `QFileDialog`) the documentation should reflect that
