### ISSUE TITLE
Don't delete QtCore.{pyqtSignal,pyqtSlot,pyqtProperty}

### ISSUE THREAD

**Issue by kernc** [spyder-ide/qtpy#76]
The [README says](https://github.com/spyder-ide/qtpy/blob/8f4207d88e4c83e71890ab54d0c80179c19b74ce/README.md#description) the API is [PyQt5 compatible](http://pyqt.sourceforge.net/Docs/PyQt5/signals_slots.html#defining-new-signals-with-pyqtsignal), yet the PyQt5 identifiers such as `QtCore.pyqtSignal` are [explicitly deleted](https://github.com/spyder-ide/qtpy/blob/31dbc9eb01329af3d7d67cbfd6ee76a632aa84c2/qtpy/QtCore.py#L24) in favor of PySide's.

PyQt5's symbols were removed in https://github.com/spyder-ide/qtpy/pull/47 with IMHO not so great justification:

> I still think that the duplicate imports are very weird and not needed

**Comment by Nodd** [comment]
The README doesn't claim to be PyQt5 compatible. It uses the PyQt5 layout for modules (other abstraction modules import everything into both QtGui and QtWidgets for example).
In "Basically, you write your code as if you were using PyQt5", the important word is "basically" :wink: It's not the case for Signals and Slot.

On the other hand we agree that the documentation is lacking, see #61.

**Comment by kernc** [comment]
Equivalently, you could [import PySide's Signal](https://github.com/spyder-ide/qtpy/blob/31dbc9eb01329af3d7d67cbfd6ee76a632aa84c2/qtpy/QtCore.py#L41):
```py
from PySide.QtCore import Signal as pyqtSignal
```
Furthermore, you could agnostically:
```py
if PYQT5:
    from PyQt5.QtCore import *
    Signal, Slot, Property = pyqtSignal, pyqtSlot, pyqtProperty
if PYSIDE:
    from PySide.QtCore import *
    pyqtSignal, pyqtSlot, pyqtProperty = Signal, Slot, Property
``` 
and avoid tensions to force the user to write their software in a certain way.

**Comment by ccordoba12** [comment]
@Nodd, your final thoughts on this? You were the one who proposed #47 :-)

I'm -0.5 on the idea because (as I said) I'd prefer projects use the more generic `Signal` instead of `pyqtSignal`. But I understand this can be hard for big projects like Orange which decided to use `pyqtSignal` from the beginning :-)

**Comment by kernc** [comment]
I don't think we will have much problem switching to Signals and Slots here. There just isn't a reason to enforce a particular style someone randomly decided upon when working to convenience the user can prove as fruitful and, in this case, so effortless.

**Comment by goanpeca** [comment]
Hi @kernc just to update here, 

>There just isn't a reason to enforce a particular style someone randomly decided

Its not really random, the thing is that we follow the Qt5 layout (not the PyQt5 layout) so we need to update the readme.

Since having PyQtSignal was PyQt5 specific, that is why we decided to remove it. PySide (and eventually PySide2) will use Signal and Slot (which feels much better).

We can re-add them if that would make the use of QtPy in orange easier... (but I still think using Signal and Slot to be better than PyQtSignal and PyQtSlot)

**Comment by rlaverde** [comment]
This is somehow related to #115

**Comment by goanpeca** [comment]
Yep, this is now updated, we should close

**Comment by raidsan** [comment]
not use spyder,  just want to use PyQt4, PyQt5 compatible,  if you delete pyqtSignal and pyqtSlot and use SIgnal/Slot in spyder way,  why not rename the project to spyder-qt ?

**Comment by ccordoba12** [comment]
Where in this discussion do we say that we decided to use Signal and Slot due to Spyder? The only mention to Spyder is yours.
